# Generated by Django 4.1.6 on 2023-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('place_type', models.CharField(choices=[('MOUNTAIN', 'MOUNTAIN')], max_length=9)),
                ('image_url', models.CharField(max_length=255)),
                ('source_url', models.CharField(max_length=255)),
                ('lon', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
            ],
        ),
    ]
